# In this script, you can find how to extract features (topics)

# Import required packages

In [ ]:
import pandas as pd
import numpy as np
import math
from google.colab import drive, files
from sklearn.decomposition import NMF
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
drive.mount('/content/drive/', force_remount=True)

Mounted at /content/drive/

In [ ]:
# "dataset_dir" is the folder which has the Train and Test datasets
# you should create this folder uploading datasets in the repo.
dataset_dir = '/content/drive/My Drive/peak/dataset_dir'

df_train = pd.read_csv(dataset_dir +"/df_train.csv")
df_test = pd.read_csv(dataset_dir +"/df_test.csv")

# Topic Modeling using Non-negative Matrix Factorization (NMF) <br>
\begin{equation}
X \approx W \times H
\end{equation}
<BR>
X: (image, tag), W: (image, topic), H: (topic, tag) matrices <br>
[sklearn - NMF](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.NMF.html) <br>
# Term Frequency-Inverse Document Frequency (TF-IDF) <br>
**Term Frequency:** the number of times a tag appears in an image. <br>
**Inverse Document Frequency:** total images in Training data over number of images with tag. <br>
[sklearn TF-IDF](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html) <br>

In [ ]:
# Use TF-IDF to weight tags
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
X = tfidf_vectorizer.fit_transform(df_train.cleaned_tags).toarray()
print("TFIDF's features: ", tfidf_vectorizer.get_feature_names_out())

TFIDF's features:  ['abandoned' 'abbey' 'abdomen' ... 'zoo' 'zoology' 'zoom']

In [ ]:
number_of_topics = 20
nmf_model = NMF(n_components=number_of_topics, init='random', random_state=5)
nmf_features = nmf_model.fit_transform(X)

/usr/local/lib/python3.10/dist-packages/sklearn/decomposition/_nmf.py:1665: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(

In [ ]:
# Show tags in the Training data with topic-association
components_df = pd.DataFrame(nmf_model.components_, columns = tfidf_vectorizer.get_feature_names_out())
components_df

,abandoned,abbey,abdomen,abend,aboriginal,absorber,abstract,abstraction,abundance,academia,...,young,youth,zebra,zen,zion,zip_up,zombie,zoo,zoology,zoom
0,0.000000,0.000000,0.000000,0.000293,0.000042,0.000000e+00,0.000000,0.000708,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.001678,0.000372,0.000000,0.000000,0.000000,0.000780,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,1.251219e-04,0.000000,0.001893,0.000000,0.000000,...,0.033148,0.000000,0.000000,0.000000,0.000000,0.000278,0.000000,0.000000,0.000000,0.000561
2,0.128161,0.006897,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000622,0.000000,0.000256,...,0.000000,0.000000,0.000000,0.000571,0.000000,0.000003,0.000000,0.000000,0.000000,0.000000
3,0.019752,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000174,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.357065,0.000000,0.000868,0.000000,0.000000,0.000000,0.000000,0.079168,0.005091,0.000000
5,0.011062,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000541,0.000000,0.000547,0.000000,0.000000,0.047701,0.002408,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000112,0.005800,0.000000,...,0.018059,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000039,0.020750
7,0.000000,0.000000,0.000000,0.001695,0.001386,0.000000e+00,0.000000,0.000000,0.003680,0.000000,...,0.000000,0.000000,0.000000,0.001056,0.000000,0.000000,0.001347,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.008706,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.033212,0.000000,0.004537,0.000159,0.000000,0.000000e+00,0.124273,0.000459,0.000000,0.000000,...,0.000000,0.002936,0.000000,0.000000,0.000000,0.000000,0.018919,0.000000,0.000000,0.012272
10,0.000000,0.000000,0.000589,0.000000,0.000087,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.014420,0.000000,0.000000,0.000000,0.000197,0.003645,0.000000,0.000000,0.000000
11,0.000000,0.000147,0.001759,0.000000,0.000000,9.263138e-07,0.021951,0.000000,0.000922,0.000000,...,0.000000,0.000000,0.000000,0.008040,0.000000,0.000000,0.000000,0.000000,0.000511,0.000000
12,0.025273,0.000000,0.000000,0.000956,0.000000,3.784355e-04,0.000000,0.001155,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.012263
13,0.000000,0.000000,0.000655,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000444,0.000000,...,0.040126,0.034797,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,0.000000,0.000000,0.002016,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.041812,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.001156,0.000000,0.000000,...,0.000000,0.002171,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,0.040427,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.944191,0.002223,0.000000,0.000095,...,0.000000,0.000000,0.000208,0.002757,0.000000,0.001615,0.001195,0.000000,0.000129,0.001842
17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.090087,0.000155,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000075,0.000066,0.000112,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.013607,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,0.000000,0.000000,0.008345,0.000000,0.000120,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,1.587562,0.004693,0.000000,0.000000,0.000000,0.000346,0.000000,0.000000,0.000000,0.000000

In [ ]:
# Show the top 20 most associated tags with topics
individual_topic_dict = {}
for topic in range(components_df.shape[0]):
    tmp = components_df.iloc[topic]
    individual_topic_dict[topic] = list(tmp.nlargest(20).keys())

df_train_topic_tag = pd.DataFrame.from_dict(individual_topic_dict)
df_train_topic_tag

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,sea,recreation,architecture,room,mammal,park,business,group,concert,monochrome,wear,flower,transportation_system,baby,togetherness,administration,design,sunset,snow,fashion
1,beach,competition,building,furniture,pet,nature,technology,festival,performance,dark,man,flora,vehicle,son,enjoyment,election,desktop,dawn,cold,pretty
2,water,leisure,city,indoors,animal,wood,text,religion,musician,nude,portrait,leaf,road,child,friendship,leader,art,evening,winter,model
3,ocean,motion,urban,seat,dog,tree,internet,battle,singer,model,adult,garden,car,little,family,league,illustration,sun,ice,sexy
4,seashore,fun,travel,table,cute,outdoors,computer,crowd,band,face,facial_expression,color,street,innocence,facial_expression,meeting,retro,dusk,frost,glamour
5,travel,lifestyle,street,chair,canine,landscape,paper,street,stage,black_and_white,music,bright,wheel,toddler,child,politician,abstract,light,weather,beautiful
6,sky,adult,house,interior_design,looking,summer,indoors,offense,music,studio,woman,floral,traffic,fun,happiness,education,pattern,sky,frozen,young
7,lake,child,outdoors,family,fur,environment,telephone,drag_race,festival,art,people,closeup,action,cute,love,banking,decoration,silhouette,tree,girl
8,sand,outdoors,old,window,domestic,grass,industry,man,guitar,profile,indoors,growth,travel,toy,adolescent,school,texture,landscape,season,hair
9,seascape,action,town,house,sit,fall,facts,police,instrument,eye,outfit,summer,drive,girl,woman,business,vintage,backlit,snowstorm,woman
10,landscape,people,sky,home,little,daylight,commerce,celebration,guitarist,girl,movie,petal,race,joy,fun,room,color,fog,landscape,portrait
11,summer,man,no_person,contemporary,cat,outside,symbol,commerce,stringed_instrument,adult,musician,blooming,fast,family,group_together,adult,symbol,fair_weather,frosty,cute
12,river,wear,window,lamp,puppy,leaf,communication,city,pop_music,side_view,girl,nature,industry,happiness,laughing,group,old,moon,wood,eye
13,vacation,boy,tourism,museum,funny,relaxation,data,people,light,woman,child,beautiful,hurry,portrait,man,democracy,graphic,reflection,icee,face
14,nature,girl,daylight,trading_floor,portrait,leisure,no_person,market,jazz,portrait,lid,no_person,city,boy,indoors,chair,vector,water,no_person,elegant
15,rock,uniform,light,inside,eye,no_person,office,group_together,energy,people,actor,food,bus,smile,education,furniture,paper,dark,nature,dress
16,island,woman,cityscape,wood,kitten,travel,money,war,microphone,man,fashion,season,railway,funny,group,congress,painting,no_person,frosty_weather,people
17,outdoors,helmet,tower,desk,young,fair_weather,illustration,woman,people,shadow,monochrome,desktop,bike,people,leisure,soccer,no_person,nature,fog,lips
18,reflection,adolescence,home,exhibition,no_person,wildlife,horizontal,adult,man,fashion,group,love,accident,face,adult,home,image,tree,outdoors,person
19,sunset,athlete,wall,sofa,sleep,vertical,number,exhibition,adult,blur,sit,delicate,automotive,cheerful,table,people,shape,lake,storm,skin

# Predict Topic Distributions of Test Data

In [ ]:
# Transform the TF-IDF
X_test = tfidf_vectorizer.transform(df_test.cleaned_tags)
nmf_features_test = nmf_model.transform(X_test)
pd.DataFrame(nmf_features_test)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.000000,0.000000,0.003894,0.004360,0.000000,0.021853,0.008524,0.000000,0.000000,0.000000,0.077317,0.000000,0.000000,0.000000,0.151370,0.005432,0.000000,0.000000,0.000000,0.003094
1,0.000000,0.000000,0.000000,0.000701,0.000000,0.000000,0.000000,0.008343,0.000000,0.000000,0.076507,0.000000,0.000000,0.000000,0.147227,0.056369,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.001332,0.021806,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.016424,0.111895,0.000000,0.117735,0.044491,0.000000,0.000000,0.000000,0.004922,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050547,0.105778,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.022150
4,0.000323,0.000000,0.000000,0.048821,0.000072,0.000000,0.000000,0.000000,0.000000,0.000000,0.028621,0.000000,0.000000,0.006318,0.000000,0.000000,0.039204,0.000000,0.000415,0.005294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0.000000,0.000000,0.000000,0.000000,0.000835,0.002024,0.000932,0.000000,0.000000,0.000000,0.000000,0.002136,0.168007,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4996,0.000000,0.000000,0.000000,0.000000,0.000000,0.163886,0.000000,0.000000,0.000000,0.000000,0.000000,0.109700,0.000000,0.000000,0.000000,0.000000,0.000000,0.028264,0.014342,0.000000
4997,0.068881,0.000000,0.087164,0.000000,0.000000,0.000873,0.040323,0.014768,0.000000,0.000000,0.000000,0.000000,0.085690,0.000280,0.000000,0.004548,0.000000,0.000000,0.000000,0.000037
4998,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.028616,0.000000,0.026094,0.000000,0.000000,0.006354,0.000000,0.068457,0.148388,0.000000,0.000000
4999,0.036439,0.000000,0.040545,0.000000,0.000000,0.129757,0.000000,0.000000,0.001979,0.000000,0.000000,0.026541,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.017557,0.000000

In [ ]:
# Prepare input files for the training and the test
train_input = pd.DataFrame(nmf_features).to_numpy()
test_input = pd.DataFrame(nmf_features_test).to_numpy()

train_label = np.array(df_train.normalizedpublic)
train_label = np.array(list(map(lambda x: math.floor(x), train_label)))
test_label = np.array(df_test.normalizedpublic)

train_input.shape, test_input.shape, train_label.shape, test_label.shape

((27000, 20), (5000, 20), (27000,), (5000,))